name: Full DevSecOps Pipeline

on: [push]

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Bandit Security Scanner
        run: pip install bandit

      - name: Run Python Security Scan
        run: bandit -r .

      - name: Run Log Analyzer
        run: python3 analyzer.py

      - name: Build Docker Image
        run: docker build -t python-log-analyzer .

      - name: Run Docker Container
        run: docker run python-log-analyzer
